export default {

    PICKING_PHASE: 'VOTING_PHASE',
    RESULTS_PHASE: 'RESULTS_PHASE',

    ABSTAIN_VALUE: 'ABSTAIN',

    ROOM_STATUS_ACTIVE: 'ACTIVE',
    ROOM_STATUS_INACTIVE: 'INACTIVE',
    ROOM_STATUS_UNKNOWN: 'UNKNOWN',

}